// Generated by CoffeeScript 1.10.0
(function() {
  var AuthenticationManager, SampleLogic, SpinCycle, app, authMgr, cors, express, logic, messageRouter, port, server;

  SpinCycle = require('spincycle');

  AuthenticationManager = require('./AuthenticationManager');

  SampleLogic = require('./SampleLogic');

  express = require("express");

  cors = require('cors');

  app = express();

  server = require("http").createServer(app);

  port = process.env.PORT || 3003;

  server.listen(port, function() {
    console.log("Server listening at port %d", port);
  });

  app.use(express["static"]("./"));

  app.use(cors());

  authMgr = new AuthenticationManager();

  messageRouter = new SpinCycle(authMgr);

  new SpinCycle.HttpMethod(messageRouter, app, '/api/');

  new SpinCycle.WsMethod(messageRouter, server);

  logic = new SampleLogic(messageRouter);

}).call(this);

//# sourceMappingURL=mock-server.js.map
